
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{secrets.REGISTRY_USERNAME}}/my-resume .

      - name: Login and push image
        run: |
          docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRYPASS}}
          docker push ${{secrets.REGISTRY_USERNAME}}/my-resume
