name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.REGISTRY_USERNAME}}/my-resume:${{github.run_number}} .
          docker build -t ${{secrets.REGISTRY_USERNAME}}/my-resume .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{secrets.REGISTRY_USERNAME}}/my-resume:${{github.run_number}}'
          format: 'table'
          exit-code: '1'   # Fails build if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Login and push image
        run: |
          docker login -u "${{secrets.REGISTRY_USERNAME}}" -p "${{secrets.REGISTRY_PASS}}"
          docker push ${{secrets.REGISTRY_USERNAME}}/my-resume:${{github.run_number}}
          docker push ${{secrets.REGISTRY_USERNAME}}/my-resume

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # port: ${{ secrets.PORT }}  # Uncomment if using a non-default port
          script: |
            docker rm -f resume || true
            docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/my-resume:${{ github.run_number }}
