
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t mfaumea/my-resume .

      - name: Login and push image
        run: |
          docker login -u mfaumea -p Mfamari@1989
          docker push mfaumea/my-resume
